embedding_size: 64
feat_embed_dim: 64
weight_size: [64, 64]

lambda_coeff: 0.9
n_mm_layers: 1

n_ui_layers: 2
knn_k: [10]
#baby 20 sports 10
co_topk: [20]
#baby 20 sports 15

cl_loss: [0.01]
#baby 0.001 sports 0.01
tau: [0.2]

mm_image_weight: [0.1]
#baby 0.1/0.3  sports 0.1
dropout: [0.9]
#[0.8, 0.9][0.8],原方法0.9
hyper_parameters: ["tau","dropout", "knn_k","co_topk","cl_loss","mm_image_weight"]
